using System.Collections.Generic;
using System.Diagnostics;
using System.IO;

namespace Midterm_Project_for_Group
{
    // jon
    class Recipt
    {
        static bool run = true;
        public Recipt(List<MenuItem> orderBasket, string reciptLine, int customerNumber, double tax, double subTotal)
        {
            run = true;

            while (run == true)
            {
                using (FileStream filestream = File.Create("Customer" + customerNumber + ".txt"))
                using (StreamWriter writer = new StreamWriter(filestream))
                {

                    writer.WriteLine("Thank you customer " + customerNumber + " for dining with us");
                    writer.WriteLine("Item:\t\t\t Cost");
                    writer.WriteLine();
                    foreach (MenuItem item in orderBasket)
                    {
                        writer.WriteLine(item.itemName + "\t\t" + item.itemCost);
                    }
                    writer.WriteLine();
                    writer.WriteLine();
                    writer.WriteLine("\t\t\t\t SubTotal = " + subTotal);
                    writer.WriteLine("\t\t\t\t Tax = " + tax);
                    writer.WriteLine();
                    writer.WriteLine(reciptLine);
                    writer.WriteLine();
                    writer.WriteLine("Have a great day!");
                    writer.WriteLine("       `:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::`      ");
                    writer.WriteLine("     *WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*    ");
                    writer.WriteLine("   `WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#`  ");
                    writer.WriteLine("  `WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW` ");
                    writer.WriteLine("  +WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+ ");
                    writer.WriteLine(" :WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW:");
                    writer.WriteLine(" +WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+");
                    writer.WriteLine(" #WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#+++#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*******+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*******+#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#*+++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#**++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWW#*+++++++++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#*+++++++++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWW*+++++++++++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*+++++++++++++++++++*WWWWWWWWWWWWWWWWWWWWWWW++++++++++++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*++++++++****++++++++*+WWWWWWWWWWWWWWWWWWWWW#*++++++++****++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++*#WW#+*+++++++*WWWWWWWWWWWWWWWWWWWWW*+++++++*+#WW#+*++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#*+++++++*WWWWWW+*++++++++WWWWWWWWWWWWWWWWWWW+*++++++*+WWWWWW++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW++++++++*WWWWWWWW+*++++++*#WWWWWWWWWWWWWWWWWW*++++++++WWWWWWWW*+++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*++++++*#WWWWWWWWW*++++++++WWWWWWWWWWWWWWWWW+*++++++*WWWWWWWWW#*++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWW*++++++++WWWWWWWWWW#*++++++*#WWWWWWWWWWWWWWWW*++++++*#WWWWWWWWWW+*++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWW+*++++++*WWWWWWWWWWWW+++++++*+WWWWWWWWWWWWWWW+*++++++*WWWWWWWWWWWW*++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWW*++++++++WWWWWWWWWWWW#*++++++*WWWWWWWWWWWWWWW*++++++*#WWWWWWWWWWWW+*++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWW+*++++++*#WWWWWWWWWWWWW+++++++*+WWWWWWWWWWWWW#*++++++*WWWWWWWWWWWWWW*++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWW*++++++++WWWWWWWWWWWWWW#*++++++*WWWWWWWWWWWWW+++++++*#WWWWWWWWWWWWWW+*++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWW+*++++++*#WWWWWWWWWWWWWWW*++++++*#WWWWWWWWWWWW*++++++*WWWWWWWWWWWWWWWW*++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWW*+++++++*WWWWWWWWWWWWWWWW+*+++++*+WWWWWWWWWWW#*+++++++WWWWWWWWWWWWWWWW++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWW+*++++++*+WWWWWWWWWWWWWWWW#*++++++*WWWWWWWWWWW+++++++*#WWWWWWWWWWWWWWWW#*++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWW*+++++++*WWWWWWWWWWWWWWWWWW*++++++*#WWWWWWWWWW*++++++*WWWWWWWWWWWWWWWWWW*+++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWW+*++++++++WWWWWWWWWWWWWWWWWW+*+++++*+WWWWWWWWW#*+++++++WWWWWWWWWWWWWWWWWW+*++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWW*+++++++*#WWWWWWWWWWWWWWWWWW#*++++++*WWWWWWWWW+++++++*#WWWWWWWWWWWWWWWWWW#*+++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWW#*+++++++*WWWWWWWWWWWWWWWWWWWW*++++++*#WWWWWWWW*++++++*WWWWWWWWWWWWWWWWWWWW*+++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWW++++++++++WWWWWWWWWWWWWWWWWWWW+++++++*+WWWWWWW#*++++++*WWWWWWWWWWWWWWWWWWWW+*+++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWW*+++++++*+WWWWWWWWWWWWWWWWWWWW+*+++++++WWWWWWW+*+++++*+WWWWWWWWWWWWWWWWWWWW#*+++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWW+*+++++++*WWWWWWWWWWWWWWWWWWWWW#*++++++*WWWWWWW*++++++*#WWWWWWWWWWWWWWWWWWWWW*+++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWW*++++++++*WWWWWWWWWWWWWWWWWWWWWW*++++++*#WWWWWW*++++++*#WWWWWWWWWWWWWWWWWWWWW+++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWW#*+++++++*+WWWWWWWWWWWWWWWWWWWWWW+++++++*+WWWWW#*++++++*WWWWWWWWWWWWWWWWWWWWWW#*+++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWW+*+++++++*#WWWWWWWWWWWWWWWWWWWWWW+*+++++++WWWWW+*+++++++WWWWWWWWWWWWWWWWWWWWWWW*+++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWW*++++++++*WWWWWWWWWWWWWWWWWWWWWWW#*++++++*WWWWW*++++++*+WWWWWWWWWWWWWWWWWWWWWWW*++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWW#*+++++++++WWWWWWWWWWWWWWWWWWWWWWW#*++++++*#WWWW*++++++*#WWWWWWWWWWWWWWWWWWWWWWW+*+++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWW+*+++++++*+WWWWWWWWWWWWWWWWWWWWWWWW*++++++*+WWW#*++++++*#WWWWWWWWWWWWWWWWWWWWWWW#*+++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWW*++++++++*#WWWWWWWWWWWWWWWWWWWWWWWW*++++++++WWW+*++++++*WWWWWWWWWWWWWWWWWWWWWWWWW*++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWW#*++++++++*WWWWWWWWWWWWWWWWWWWWWWWWW++++++++*WWW+++++++++WWWWWWWWWWWWWWWWWWWWWWWWW*++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWW+++++++++++WWWWWWWWWWWWWWWWWWWWWWWWW+*++++++*WWW*++++++++WWWWWWWWWWWWWWWWWWWWWWWWW+++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWW*++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWW#*++++++*#WW*++++++*+WWWWWWWWWWWWWWWWWWWWWWWWW+*++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWW#*++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWW#*++++++*+W#*++++++*#WWWWWWWWWWWWWWWWWWWWWWWWW#*++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWW+*++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWW*++++++*+W+*++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWW*++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWW*+++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWW*++++++++W+*++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWW++++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWW*++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWW+++++++++W++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWW+*++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWW#*++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWW+++++++++#+++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWW#*++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWW++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWW#*++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWW*+++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWW*+++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWW#*+++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWW#*+++++++++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWW++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWW+*++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWW#*+++++++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWW+*++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWW++++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWW*+++++++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWW*+++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWW*+++++++++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWW#*+++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWW#*+++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWW*+++++++++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*+++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWW+*+++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW++++++++++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*+++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWW+++++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+++++++++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW++++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWW*+++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWW#*+++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWW#*+++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#*+++++++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#*+++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWW+*+++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#*+++++++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#*+++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWW+++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#*+++++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*++++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWW*++++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#*+++++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*++++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWW*++++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*+++++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWW#*+++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW***************#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+***********+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWW+*+++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+++++++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#++++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWW+++++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWW*++++++++++*+WWW*`::`WWWW+`::`#WWWWWWWWWWWWWWW:::::::::*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*`:`WWWWWWWWWW::::W+`:WWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWW*++++++++++*#WWW`    +WWW:    *WWWWWW###WWWWWW:          :WWWWWWWW###WWWWWWWWWWWWW###WWWWWWWW####WWWWW:   #WWWWWWWWW   `W* :WWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWW#*++++++++++*#WWW`    :WWW     :WWWW#`    `#WWW:           `WWWWW+`    `+WWW* ` *:    `#WWWW:      :WWW: ` #WWWW*::*#   `W* *WW#*::**#WWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWW+*++++++++++*WWWW     `WW+     :WWW+        #WW:   `+++:    :WWW:        +WW*      `    #WW:        `WW: ` #WW*         `W+`#W:       *WWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWW+*++++++++++*WWW#      #W*     `WWW   `**`  `WW:   :WWWW:    WW+ ` `**`   #W*           *W#   :WW: ` +W: ` #W+          `WWWW+  `#W:   #WWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWW++++++++++++*WWW*      *W`      WW* ` #WW# ` +W:   :WWWWW    +W`  `WWW#   *W*    +W+    *WWWWWWWW* ` +W: ` #W`   *WW:   `WWWW:  :WWW+++WWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWW*+++++++++++*WWW:  `:  :W  `:   #W:  `WWWWWWWWW:   :WWWWW`   *W   *WWWW:  `W* ` *WWW* ` *WWWW+**:    +W: ` WW   :WWWW   `WWWW: ` :+#WWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWW*++++++++++++WWW:  `#  `*  :+ ` +W`  :WWWWWWWWW:   :WWWWW`   *W ` +WWWW:  `W* ` #WWW+ ` *WW*         +W: ` W# ` +WWWW   `WWWW#       :#WWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWW#*++++++++++++WWW`  :W`     *W   *W`  :WWWWWWWWW:   :WWWWW    +W ` *WWWW:  `W* ` +WWW+ ` *W*   *WW* ` +W: ` W# ` +WWWW   `WWWWWW*:`     #WWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWW#*++++++++++*+WWW   :W:     #W   :W:  `WWWW+#+WW:   :WWWW*    WW   :WWWW`  `W* ` +WWW+ ` *W   `WWW* ` +W: ` WW ` *WWWW   `WWWWWWWWW#` ` :WWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWW#*++++++++++*+WW# ` *W+     WW`  `W# ` *WW*   #W:   :WWW*    :WW:   +WW* ` *W* ` +WWW+ ` *W    #W+    +W: ` #W    #WW*   `WWWW::`*WW# ` :WWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWW+*++++++++++*+WW+ ` +WW    :WW:   WW: ` `` ` :WW:           `WWW#    ``   `WW* ` #WWW+ ` *W`        ` +W: ` #W* ` `::    :WWWW`   +#: ` +WWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWW+*++++++++++*#WW* ` #WW`   *WW*   #WW`      :WWW:          `WWWWW+       `WWW* ` +WWW+ ` *W+     `:   +W:   #WW:         `WWWW+        :WWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWW++++++++++++*#WW:```WWW* ` #WW+ ` #WWW+:``:+WWWW:````````:+WWWWWWWW*```:*WWWW#:*:#WWW#:*:+WW#:``:W#:*:#W+:*:WWWW+:``:#****WWWWW#:````:+WWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWW*+++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWW*+++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#############WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#############WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWW*+++++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#*************+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*************#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWW#*+++++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#*+++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*+++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWW#*+++++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#*+++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*+++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWW#*+++++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#*+++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*+++++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWW#*+++++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#*+++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW++++++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWW+*+++++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#*+++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW++++++++++++*+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWW+*+++++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*+++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW++++++++++++++WWWWWW#WWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWW+*++++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*+++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW++++++++++++++WWWWWWW###WWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWW++++++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*+++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW++++++++++++++WWWWWWW+WW+WWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWW++++++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*+++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++++++*WWWWWWW+WW+WWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWW++++++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*+++++++++++*#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++++++*WWWWWWW+#+WWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWW++++++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++++++*WWWWWWW+WW+WWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWW++++++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++++++*WWWWWWWWWW#WWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWW++++++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++++++*WWWWWWWWWWW#WWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWW++++++++++++++WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*+++++++++++*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWW*************+WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+*************WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWW#############WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#############WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" #WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#");
                    writer.WriteLine(" +WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+");
                    writer.WriteLine(" :WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW:");
                    writer.WriteLine("  WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW ");
                    writer.WriteLine("  :WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW: ");
                    writer.WriteLine("   *WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW*  ");
                    writer.WriteLine("    :WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW:   ");
                    writer.WriteLine("      :+#############################################################################################################################################+:     ");

                    writer.Close();
                    run = false;
                    Process.Start("Customer" + customerNumber + ".txt");
                }
            }
        }
    }
}